# Generated by Django 4.2.7 on 2023-12-03 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(default='Apo', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(default='Apo', max_length=15)),
                ('no_files_uploaded', models.IntegerField(default=0)),
                ('registration_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='file_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('file_url', models.URLField(default='')),
                ('date', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api_.users')),
            ],
        ),
    ]
