# Generated by Django 4.2.7 on 2023-12-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_', '0002_remove_file_data_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_data',
            name='unique_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
