# Generated by Django 4.2.7 on 2023-12-04 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_', '0003_file_data_unique_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='file_data',
            new_name='file_datas',
        ),
    ]
