# Generated by Django 4.2.7 on 2023-12-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_', '0004_rename_file_data_file_datas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_datas',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
