# Generated by Django 4.2.7 on 2023-12-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_', '0007_delete_file_datas'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_datas',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.FileField(upload_to='')),
                ('file_url', models.URLField(default='')),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
    ]
